const products = [
  {
    id: 1,
    name: "iPhone 12 Pro",
    brand: "Apple",
    category: "Smartphones",
    desc: "6.1-inch display",
    price: 999,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947593/iphone12pro_xcz7ds.jpg",
  },
  {
    id: 2,
    name: "iPhone 12",
    brand: "Apple",
    category: "Smartphones",
    desc: "5.4-inch mini display",
    price: 699,
    image:
      "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/iphone12_qrt2jy.jpg",
  },
  {
    id: 3,
    name: "Galaxy S",
    category: "Smartphones",
    brand: "Samsung",
    desc: "6.5-inch display",
    price: 399,
    image:
      "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947926/galaxyS_sm8fcv.png",
  },
  {
    id: 4,
    name: "EliteBook",
    brand: "HP",
    category: "Laptops",
    desc: "14.3-inch display, Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz   2.71 GHz, Install RAM 8GB",
    price: 40000,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/HP_obhhvy.webp",
  },
  {
    id: 5,
    name: "Dell XPS 13",
    brand: "DELL",
    category: "Laptops",
    desc: "13-inch Retina display,Intel(R) Core(TM) i7-9300U CPU @ 2.60GHz   2.71 GHz, Install RAM 16GB",
    price: 999,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/dell_z2dcgk.jpg",
  },
  {
    id: 6,
    name: "Tosheba",
    brand: "Tosheba",
    category: "Laptops",
    desc: "13-inch Retina display,Intel(R) Core(TM) i7-9300U CPU @ 2.60GHz   2.71 GHz, Install RAM 16GB",
    price: 999,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947928/toshiba_ljrwxf.jpg",
  },
  {
    id: 7,
    name: "MacBook Air",
    brand: "Apple",
    category: "Laptops",
    desc: "13-inch Retina display",
    price: 999,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/mac_oujzwm.avif",
  },
  {
    id: 8,
    name: "HP LaserJet",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/Printer_rndnx0.webp",
  },
  {
    id: 9,
    name: "HP LaserJet pro 400",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/pro_ewbt9i.webp",
  },
  {
    id: 10,
    name: "HP LaserJet 1320",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947927/pro12_af3q1d.webp",
  },
  {
    id: 12,
    name: "HP LaserJet pro scanner and printer",
    brand: "HP",
    category: "Printers",
    desc: "Wireless laser printer",
    price: 249,
    image: "https://res.cloudinary.com/djqcbu4jl/image/upload/v1740947928/scanner_sisifs.avif",
  },
];

module.exports = products;