const products = [
  {
    id: 1,
    name: "iPhone 12 Pro",
    brand: "Apple",
    category: "Smartphones",
    desc: "6.1-inch display",
    price: 999,
    image: "http://localhost:5000/images/iphone12pro.jpg",
  },
  {
    id: 2,
    name: "iPhone 12",
    brand: "Apple",
    category: "Smartphones",
    desc: "5.4-inch mini display",
    price: 699,
    image:
      "http://localhost:5000/images/iphone12.jpg",
  },
  {
    id: 3,
    name: "Galaxy S",
    category: "Smartphones",
    brand: "Samsung",
    desc: "6.5-inch display",
    price: 399,
    image:
      "http://localhost:5000/images/galaxyS.png",
  },
  {
    id: 4,
    name: "EliteBook",
    brand: "HP",
    category: "Laptops",
    desc: "14.3-inch display, Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz   2.71 GHz, Install RAM 8GB",
    price: 40000,
    image: "http://localhost:5000/images/HP.webp",
  },
  {
    id: 5,
    name: "Dell XPS 13",
    brand: "DELL",
    category: "Laptops",
    desc: "13-inch Retina display,Intel(R) Core(TM) i7-9300U CPU @ 2.60GHz   2.71 GHz, Install RAM 16GB",
    price: 999,
    image: "http://localhost:5000/images/dell.jpg",
  },
  {
    id: 6,
    name: "Tosheba",
    brand: "Tosheba",
    category: "Laptops",
    desc: "13-inch Retina display,Intel(R) Core(TM) i7-9300U CPU @ 2.60GHz   2.71 GHz, Install RAM 16GB",
    price: 999,
    image: "http://localhost:5000/images/toshiba.jpg",
  },
  {
    id: 7,
    name: "MacBook Air",
    brand: "Apple",
    category: "Laptops",
    desc: "13-inch Retina display",
    price: 999,
    image: "http://localhost:5000/images/mac.avif",
  },
  {
    id: 8,
    name: "HP LaserJet",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "http://localhost:5000/images/Printer.webp",
  },
  {
    id: 9,
    name: "HP LaserJet pro 400",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "http://localhost:5000/images/pro.webp",
  },
  {
    id: 10,
    name: "HP LaserJet 1320",
    brand: "HP",
    category: "Printers",
    desc: "Wireless monochrome laser printer",
    price: 249,
    image: "http://localhost:5000/images/pro12.webp",
  },
  {
    id: 12,
    name: "HP LaserJet pro scanner and printer",
    brand: "HP",
    category: "Printers",
    desc: "Wireless laser printer",
    price: 249,
    image: "http://localhost:5000/images/scanner.avif",
  },
];

module.exports = products;